import image from "./image";

const products = [
    {
        id: 1,
        image: image.PPApple,
        name: "Green Apple",
        price: "$19.99",
        stars: "4",
        category: "Fruits",
        subcategory: ["Hot Deals", "popular products","Featured Products"],
        tags: ["Vegetables","Vitamin","Fruit", "Chinese", "Green", "Healthy", "Cabbage"],
      },
      {
        id: 2,
        image: image.PPOrange,
        name: "Fresh Indian Malta",
        price: "$20",
        stars: "4",
        category: "Fruits",
        subcategory: ["Hot Deals", "popular products","Featured Products"],
        tags: ["Vegetables","Vitamin","Fruit",  "Chinese", "Green", "Healthy", "Orange"],
      },
      {
        id: 3,
        image: image.PPCabbage,
        name: "Chinese Cabbage",
        price: "$12",
        stars: "4",
        category: ["Vegetables","Cooking",],
        subcategory: ["Hot Deals", "popular products","Featured Products"],
        tags: ["Vegetables", "Chinese", "Green", "Healthy", "Cabbage"],
      },
      {
        id: 4,
        image: image.PPLettuce,
        name: "Green Lettuce",
        price: "$9",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals","Featured Products"],
        tags: ["Vegetables", "Chinese", "Green", "Healthy", "Lettuce"],
      },
      {
        id: 5,
        image: image.PPEggplant,
        name: "Eggplant",
        price: "$34",
        stars: "4",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals","Featured Products"],
        tags: ["Vegetables", "Chinese", "Healthy", "Eggplant"],
      },
      {
        id: 6,
        image: image.PPPotato,
        name: "Big Potato",
        price: "$20",
        stars: "4",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals"],
        tags: ["Vegetables", "Healthy", "Potato"],
      },
      {
        id: 7,
        image: image.PPCorn,
        name: "Corn",
        price: "$20",
        stars: "4.5",
        category:["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals"],
        tags: ["Vegetables", "Healthy", "Corn"],
      },
      {
        id: 8,
        image: image.PPCauliflower,
        name: "Fresh Cauliflower",
        price: "$12",
        stars: "4",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products"],
        tags: ["Vegetables", "Healthy", "Cauliflower"],
      },
      {
        id: 9,
        image: image.PPCapsicum,
        name: "Green Capsicum",
        price: "$9",
        stars: "4",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals"],
        tags: ["Vegetables", "Healthy", "Capsicum"],
      },
      {
        id: 10,
        image: image.PPChilly,
        name: "Fresh Chilli",
        price: "$34",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        subcategory: ["popular products","Hot Deals"],
        tags: ["Vegetables", "Healthy", "Chilli"],
      },
      {
        id: 11,
        image: image.LadyFinger,
        name: "Lady Finger",
        price: "$14.99",
        AP:"20.99",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        tags: ["Lady Finger", "Vegetable", "Green"]
      },
      {
        id: 12,
        image: image.RedCapsicum,
        name: "Red Capsicum",
        price: "$14.99",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        subcategory:["Hot Deals"],
        tags: ["Capsicum", "Vegetable", "Red"]
      },{
        id: 13,
        image: image.RedChilly,
        name: "Red Chilli",
        price: "$14.99",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        tags: ["Chilli", "Vegetable", "Red"]
      },
      {
        id: 14,
        image: image.Tomato,
        name: "Red Tomato",
        price: "$14.99",
        stars: "4.5",
        category: ["Vegetables","Cooking",],
        subcategory:["Hot Deals"],
        tags: ["Tomato","Vitamin","Fruit","Vegetable" ,"Red",]
      },
      {
        id: 15,
        image: image.Mango,
        name: "Fresh Mango",
        price: "$14.99",
        stars: "4.5",
        category: "Fruits",
        subcategory:["Hot Deals"],
        tags: ["Mango","Vitamin","Fruit",  "Fruit", "Yellow"]
      },
];

  export default products;